### PR TITLE
Add more Garfield fanart

### PR DESCRIPTION
**Pull request by P3tray**

### CODE REVIEW

**Comment by P3tray** [comment]
thanks bro

**Comment by P3tray** [comment]
you got two of these now though
image

**Comment by P3tray** [comment]
you can just click the big green merge button

**Comment by GarfieldWeb** [comment]
> thanks bro

Thank s for the the garfield art!

**Comment by P3tray** [comment]
> > thanks bro
> 
> Thank s for the the garfield art!

no worries

**Pull request closed without merging**
